# Generated by Django 4.1.2 on 2022-10-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='author',
            new_name='Creator',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='title',
            new_name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
    ]
